theme: minima

title: Kronenthaler's dumpster
description: > # this means to ignore newlines until "show_excerpts:"
  Welcome to the dumpster. Some man's trash can be another man's treasure.
  I will dump my thought here, feel free to pick any gem you find in there.

show_excerpts: true # set to true to show excerpts on the homepage

# minima plugins
plugins:
  - jekyll-seo-tag
